name       : ruby-mime-types-data
version    : 3.2020.0512
release    : 4
source     :
    - https://rubygems.org/downloads/mime-types-data-3.2020.0512.gem : a31c1705fec7fc775749742c52964a0e012968b43939e141a74f43ffecd6e5fc
license    : MIT
component  : programming.ruby
summary    : RubyGem - mime-types-data
description: |
    mime-types-data provides a registry for information about MIME media type definitions. It can be used with the Ruby mime-types library or other software to determine defined filename extensions for MIME types, or to use filename extensions to look up the likely MIME type definitions.mime-types-data provides a registry for information about MIME media type definitions. It can be used with the Ruby mime-types library or other software to determine defined filename extensions for MIME types, or to use filename extensions to look up the likely MIME type definitions.mime-types-data provides a registry for information about MIME media type definitions. It can be used with the Ruby mime-types library or other software to determine defined filename extensions for MIME types, or to use filename extensions to look up the likely MIME type definitions.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
