name       : ruby-mime-types-data
version    : 3.2016.0521
release    : 1
source     :
    - https://rubygems.org/downloads/mime-types-data-3.2016.0521.gem : 7542bccff06d70c4ad94d1cf10b7dac6bd89958356e5d0d7f6447168c819be12
license    : MIT
component  : programming.ruby
summary    : RubyGem - mime-types-data
description: |
    mime-types-data provides a registry for information about MIME media type definitions. It can be used with the Ruby mime-types library or other software to determine defined filename extensions for MIME types, or to use filename extensions to look up the likely MIME type definitions.mime-types-data provides a registry for information about MIME media type definitions. It can be used with the Ruby mime-types library or other software to determine defined filename extensions for MIME types, or to use filename extensions to look up the likely MIME type definitions.mime-types-data provides a registry for information about MIME media type definitions. It can be used with the Ruby mime-types library or other software to determine defined filename extensions for MIME types, or to use filename extensions to look up the likely MIME type definitions.
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - ruby
install    : |
    %gem_install
